name: Backend Deploy
on:
  workflow_run:
    workflows: ["Backend Build"]
    types: [completed]
    branches: [ main ]
  push:
    tags: [ 'v*' ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

defaults:
  run:
    working-directory: backend

jobs:
  fly-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@v1

    - name: Deploy to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --image ghcr.io/${{ github.repository }}:latest
