name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [ main ]
  push:
    tags: [ 'v*' ]

jobs:
  fly-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [ "mtg-labels", "mtg-printable-label" ]
    steps:
    - uses: actions/checkout@v6

    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@v1

    - name: Deploy to Fly (${{ matrix.app }})
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --image ghcr.io/${{ github.repository }}:latest --app ${{ matrix.app }}
